### ISSUE TITLE
WARNING bad messages + Coppelia does not load simRosExtInterface

### ISSUE THREAD

**Issue by Acefrrag** [CoppeliaRobotics/simExtROSInterface#1]
after cloning the content into catkin_ws/src I did

`catkin_make`

During the building I received warnings:

`Base path: /home/ubuntuadmin/catkin_ws
Source space: /home/ubuntuadmin/catkin_ws/src
Build space: /home/ubuntuadmin/catkin_ws/build
Devel space: /home/ubuntuadmin/catkin_ws/devel
Install space: /home/ubuntuadmin/catkin_ws/install
####
####
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CATKIN_DEVEL_PREFIX: /home/ubuntuadmin/catkin_ws/devel
-- Using CMAKE_PREFIX_PATH: /home/ubuntuadmin/catkin_ws/devel;/opt/ros/melodic
-- This workspace overlays: /home/ubuntuadmin/catkin_ws/devel;/opt/ros/melodic
-- Found PythonInterp: /usr/bin/python2 (found suitable version "2.7.17", minimum required is "2") 
-- Using PYTHON_EXECUTABLE: /usr/bin/python2
-- Using Debian Python package layout
-- Using empy: /usr/bin/empy
-- Using CATKIN_ENABLE_TESTING: ON
-- Call enable_testing()
-- Using CATKIN_TEST_RESULTS_DIR: /home/ubuntuadmin/catkin_ws/build/test_results
-- Found gtest sources under '/usr/src/googletest': gtests will be built
-- Found gmock sources under '/usr/src/googletest': gmock will be built
-- Found PythonInterp: /usr/bin/python2 (found version "2.7.17") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Using Python nosetests: /usr/bin/nosetests-2.7
-- catkin 0.7.23
-- BUILD_SHARED_LIBS is on
-- BUILD_SHARED_LIBS is on
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- ~~  traversing 2 packages in topological order:
-- ~~  - beginner_tutorials
-- ~~  - sim_ros_interface
-- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
-- +++ processing catkin package: 'beginner_tutorials'
-- ==> add_subdirectory(beginner_tutorials)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- beginner_tutorials: 1 messages, 1 services
-- +++ processing catkin package: 'sim_ros_interface'
-- ==> add_subdirectory(sim_ros_interface)
-- Using these message generators: gencpp;geneus;genlisp;gennodejs;genpy
-- CoppeliaSim: LIBPLUGIN_DIR: /home/ubuntuadmin/CoppeliaSim_Edu_V4_0_0_Ubuntu18_04/programming/libPlugin.
-- CoppeliaSim: COPPELIASIM_ROOT_DIR: /home/ubuntuadmin/CoppeliaSim_Edu_V4_0_0_Ubuntu18_04.
-- Found CoppeliaSim installation at /home/ubuntuadmin/CoppeliaSim_Edu_V4_0_0_Ubuntu18_04.
-- Checking CoppeliaSim header version...
-- CoppeliaSim headers version 4.0.0 rev4
-- Found Git: /usr/bin/git (found version "2.17.1") 
-- Adding simStubsGen command...
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntuadmin/catkin_ws/build
####
####
Scanning dependencies of target _beginner_tutorials_generate_messages_check_deps_Num
Scanning dependencies of target _beginner_tutorials_generate_messages_check_deps_AddTwoInts
Scanning dependencies of target std_msgs_generate_messages_lisp
Scanning dependencies of target std_msgs_generate_messages_cpp
[  0%] Built target std_msgs_generate_messages_lisp
[  0%] Built target std_msgs_generate_messages_cpp
Scanning dependencies of target std_msgs_generate_messages_eus
Scanning dependencies of target std_msgs_generate_messages_py
[  0%] Built target std_msgs_generate_messages_eus
[  0%] Built target std_msgs_generate_messages_py
[  0%] Built target _beginner_tutorials_generate_messages_check_deps_Num
[  0%] Built target _beginner_tutorials_generate_messages_check_deps_AddTwoInts
Scanning dependencies of target std_msgs_generate_messages_nodejs
Scanning dependencies of target generate_ros_code
Scanning dependencies of target beginner_tutorials_generate_messages_lisp
Scanning dependencies of target beginner_tutorials_generate_messages_cpp
[  0%] Built target std_msgs_generate_messages_nodejs
[  2%] Generating generated/adv.cpp
[  7%] Built target beginner_tutorials_generate_messages_lisp
[ 11%] Built target beginner_tutorials_generate_messages_cpp
Scanning dependencies of target beginner_tutorials_generate_messages_eus
[ 14%] Generating generated/pub.cpp
Scanning dependencies of target beginner_tutorials_generate_messages_py
[ 21%] Built target beginner_tutorials_generate_messages_eus
Scanning dependencies of target beginner_tutorials_generate_messages_nodejs
[ 30%] Built target beginner_tutorials_generate_messages_py
[ 33%] Generating generated/ros_msg_io.cpp
[ 38%] Built target beginner_tutorials_generate_messages_nodejs
Scanning dependencies of target listener
[ 40%] Building CXX object beginner_tutorials/CMakeFiles/listener.dir/src/listener.cpp.o
WARNING: bad msg: driver_base/ConfigString
WARNING: bad msg: driver_base/ConfigValue
WARNING: bad msg: driver_base/SensorLevels
WARNING: bad msg: driver_base/ConfigString
WARNING: bad msg: driver_base/ConfigValue
WARNING: bad msg: driver_base/SensorLevels
WARNING: bad msg: driver_base/ConfigString
WARNING: bad msg: driver_base/ConfigValue
WARNING: bad msg: driver_base/SensorLevels
[ 42%] Generating generated/ros_msg_io.h
[ 45%] Generating generated/ros_srv_io.cpp
WARNING: bad msg: driver_base/ConfigString
WARNING: bad msg: driver_base/ConfigValue
WARNING: bad msg: driver_base/SensorLevels
WARNING: bad msg: driver_base/ConfigString
WARNING: bad msg: driver_base/ConfigValue
WARNING: bad msg: driver_base/SensorLevels
[ 47%] Generating generated/ros_srv_io.h
[ 50%] Generating generated/srvcall.cpp
[ 52%] Linking CXX executable /home/ubuntuadmin/catkin_ws/devel/lib/beginner_tutorials/listener
[ 52%] Built target listener
Scanning dependencies of target talker
[ 54%] Building CXX object beginner_tutorials/CMakeFiles/talker.dir/src/talker.cpp.o
[ 57%] Generating generated/srvcli.cpp
[ 59%] Generating generated/srvsrv.cpp
[ 61%] Generating generated/sub.cpp
Scanning dependencies of target beginner_tutorials_gencpp
[ 61%] Built target beginner_tutorials_gencpp
Scanning dependencies of target beginner_tutorials_generate_messages
[ 61%] Built target beginner_tutorials_generate_messages
Scanning dependencies of target add_two_ints_server
WARNING: bad msg: driver_base/ConfigString
WARNING: bad msg: driver_base/ConfigValue
WARNING: bad msg: driver_base/SensorLevels
[ 64%] Building CXX object beginner_tutorials/CMakeFiles/add_two_ints_server.dir/srv/add_two_ints_server.cpp.o
WARNING: bad msg: driver_base/ConfigString
WARNING: bad msg: driver_base/ConfigValue
WARNING: bad msg: driver_base/SensorLevels
[ 66%] Linking CXX executable /home/ubuntuadmin/catkin_ws/devel/lib/beginner_tutorials/talker
Scanning dependencies of target add_two_ints_client
[ 66%] Built target generate_ros_code
[ 69%] Building CXX object beginner_tutorials/CMakeFiles/add_two_ints_client.dir/srv/add_two_ints_client.cpp.o
[ 69%] Built target talker
[ 71%] Generating generated/stubs.cpp, generated/stubs.h, generated/lua_calltips.cpp
/home/ubuntuadmin/CoppeliaSim_Edu_V4_0_0_Ubuntu18_04/programming/libPlugin/simStubsGen/generate.py --xml-file /home/ubuntuadmin/catkin_ws/src/sim_ros_interface/meta/callbacks.xml --lua-file /home/ubuntuadmin/catkin_ws/src/sim_ros_interface/simExtROSInterface.lua --gen-all /home/ubuntuadmin/catkin_ws/build/sim_ros_interface/generated
python /home/ubuntuadmin/CoppeliaSim_Edu_V4_0_0_Ubuntu18_04/programming/libPlugin/simStubsGen/external/pycpp/pycpp.py -p xml_file=/home/ubuntuadmin/catkin_ws/src/sim_ros_interface/meta/callbacks.xml -i /home/ubuntuadmin/CoppeliaSim_Edu_V4_0_0_Ubuntu18_04/programming/libPlugin/simStubsGen/cpp/stubs.cpp -o /home/ubuntuadmin/catkin_ws/build/sim_ros_interface/generated/stubs.cpp -P /home/ubuntuadmin/CoppeliaSim_Edu_V4_0_0_Ubuntu18_04/programming/libPlugin/simStubsGen
python /home/ubuntuadmin/CoppeliaSim_Edu_V4_0_0_Ubuntu18_04/programming/libPlugin/simStubsGen/external/pycpp/pycpp.py -p xml_file=/home/ubuntuadmin/catkin_ws/src/sim_ros_interface/meta/callbacks.xml -i /home/ubuntuadmin/CoppeliaSim_Edu_V4_0_0_Ubuntu18_04/programming/libPlugin/simStubsGen/cpp/stubs.h -o /home/ubuntuadmin/catkin_ws/build/sim_ros_interface/generated/stubs.h -P /home/ubuntuadmin/CoppeliaSim_Edu_V4_0_0_Ubuntu18_04/programming/libPlugin/simStubsGen
python /home/ubuntuadmin/CoppeliaSim_Edu_V4_0_0_Ubuntu18_04/programming/libPlugin/simStubsGen/lua_to_xml.py /home/ubuntuadmin/catkin_ws/src/sim_ros_interface/simExtROSInterface.lua /home/ubuntuadmin/catkin_ws/build/sim_ros_interface/generated/lua.xml
python /home/ubuntuadmin/CoppeliaSim_Edu_V4_0_0_Ubuntu18_04/programming/libPlugin/simStubsGen/merge_xml.py /home/ubuntuadmin/catkin_ws/src/sim_ros_interface/meta/callbacks.xml /home/ubuntuadmin/catkin_ws/build/sim_ros_interface/generated/lua.xml /home/ubuntuadmin/catkin_ws/build/sim_ros_interface/generated/reference.xml
xsltproc -o /home/ubuntuadmin/catkin_ws/build/sim_ros_interface/generated/reference.html /home/ubuntuadmin/CoppeliaSim_Edu_V4_0_0_Ubuntu18_04/programming/libPlugin/simStubsGen/xsl/reference.xsl /home/ubuntuadmin/catkin_ws/build/sim_ros_interface/generated/reference.xml
python /home/ubuntuadmin/CoppeliaSim_Edu_V4_0_0_Ubuntu18_04/programming/libPlugin/simStubsGen/generate_lua_calltips.py ROSInterface ROS /home/ubuntuadmin/catkin_ws/src/sim_ros_interface/simExtROSInterface.lua /home/ubuntuadmin/catkin_ws/build/sim_ros_interface/generated/lua_calltips.cpp
python /home/ubuntuadmin/CoppeliaSim_Edu_V4_0_0_Ubuntu18_04/programming/libPlugin/simStubsGen/generate_notepadplusplus_xml.py /home/ubuntuadmin/catkin_ws/build/sim_ros_interface/generated/reference.xml /home/ubuntuadmin/catkin_ws/build/sim_ros_interface/generated/np++.xml
python /home/ubuntuadmin/CoppeliaSim_Edu_V4_0_0_Ubuntu18_04/programming/libPlugin/simStubsGen/generate_notepadplusplus_txt.py /home/ubuntuadmin/catkin_ws/build/sim_ros_interface/generated/reference.xml /home/ubuntuadmin/catkin_ws/build/sim_ros_interface/generated/np++.txt
python /home/ubuntuadmin/CoppeliaSim_Edu_V4_0_0_Ubuntu18_04/programming/libPlugin/simStubsGen/generate_deprecated_txt.py /home/ubuntuadmin/catkin_ws/src/sim_ros_interface/meta/callbacks.xml /home/ubuntuadmin/catkin_ws/build/sim_ros_interface/generated/deprecated_mapping.txt
Scanning dependencies of target simExtROSInterface
[ 73%] Building CXX object sim_ros_interface/CMakeFiles/simExtROSInterface.dir/src/sim_ros_interface.cpp.o
[ 76%] Building CXX object sim_ros_interface/CMakeFiles/simExtROSInterface.dir/src/ros_msg_builtin_io.cpp.o
[ 78%] Linking CXX executable /home/ubuntuadmin/catkin_ws/devel/lib/beginner_tutorials/add_two_ints_server
[ 78%] Built target add_two_ints_server
[ 80%] Building CXX object sim_ros_interface/CMakeFiles/simExtROSInterface.dir/home/ubuntuadmin/CoppeliaSim_Edu_V4_0_0_Ubuntu18_04/programming/common/simLib.cpp.o
[ 83%] Building CXX object sim_ros_interface/CMakeFiles/simExtROSInterface.dir/home/ubuntuadmin/CoppeliaSim_Edu_V4_0_0_Ubuntu18_04/programming/libPlugin/simPlusPlus/Plugin.cpp.o
[ 85%] Building CXX object sim_ros_interface/CMakeFiles/simExtROSInterface.dir/generated/stubs.cpp.o
[ 88%] Linking CXX executable /home/ubuntuadmin/catkin_ws/devel/lib/beginner_tutorials/add_two_ints_client
[ 88%] Built target add_two_ints_client
[ 90%] Building CXX object sim_ros_interface/CMakeFiles/simExtROSInterface.dir/generated/ros_msg_io.cpp.o
[ 92%] Building CXX object sim_ros_interface/CMakeFiles/simExtROSInterface.dir/generated/ros_srv_io.cpp.o
[ 95%] Linking CXX shared library /home/ubuntuadmin/catkin_ws/devel/lib/libsimExtROSInterface.so
[100%] Built target simExtROSInterface
`

After executing roscore and launching CoppeliaSim it doesn't load the plugin.

**Comment by fferri** [comment]
This has been asked over and over on the [forum](https://forum.coppeliarobotics.com): you need to source the ROS environment before running `./coppeliaSim.sh`.

Reopen and provide additional details if that's not the case.

**Comment by Acefrrag** [comment]
Thanks for your help. When I did catkin_make he put the library inside the workspace oo catkinand not in the CoppeliaSim directory
