### ISSUE TITLE
_install TARGETS given no LIBRARY DESTINATION for shared library target   "simExtROSInterface"

### ISSUE THREAD

**Issue by rgudwin** [CoppeliaRobotics/simExtROSInterface#2]
Hi, 
I used to have sim_ros_interface working in my project, but recently the following bug started to appear, without any change in my code:
-----------------------------------
Errors     << sim_ros_interface:cmake /ros/catkin_ws/logs/sim_ros_interface/build.cmake.005.log                      
CMake Error at /opt/ros/melodic/share/catkin/cmake/custom_install.cmake:13 (_install):
  _install TARGETS given no LIBRARY DESTINATION for shared library target
  "simExtROSInterface".
Call Stack (most recent call first):
  CMakeLists.txt:81 (install)

cd /ros/catkin_ws/build/sim_ros_interface; catkin build --get-env sim_ros_interface | catkin env -si  /usr/bin/cmake /ros/catkin_ws/src/sim_ros_interface --no-warn-unused-cli -DCATKIN_DEVEL_PREFIX=/ros/catkin_ws/devel/.private/sim_ros_interface -DCMAKE_INSTALL_PREFIX=/ros/catkin_ws/install -DPYTHON_EXECUTABLE=/usr/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/include/python3.6m -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so; cd -
.....................................................................................................................
Failed     << sim_ros_interface:cmake            [ Exited with code 1 ]                                              
Failed    <<< sim_ros_interface                  [ 1.8 seconds ] 
-------------------------
I tried to track the origin of the problem, and I suspect that it was due to the following line in CMakeLists.txt, which didn't existed in the previous version which was working for me:

install(TARGETS simExtROSInterface DESTINATION ${COPPELIASIM_PLUGINS_DIR})

This line didn't existed in my previous code which was working ... I tried to set up the 
COPPELIASIM_PLUGINS_DIR environment variable with:
export COPPELIASIM_PLUGINS_DIR=/ros
just to see if the system was able to create the library somewhere, but nevertheless it didn't worked, and the same error continued.
Please, I need some light, because the problem appeared due to some change in your code in the last 2 months ... it was working in January 2020. 
Ricardo

**Comment by fferri** [comment]
You need the latest version of [libPlugin](https://github.com/CoppeliaRobotics/libPlugin/) (410537a)
