### ISSUE TITLE
sim_ext_ros_interface is not compiling

### ISSUE THREAD

**Issue by ShepelIlya** [CoppeliaRobotics/simExtROSInterface#4]
First of all, instructions that can be found [here](https://www.coppeliarobotics.com/helpFiles/en/ros1Tutorial.htm) is not actual.

Second, i think that it's a very bad decision - using cmake version that differs from standard 3.10.2 for melodic and ubuntu 18.04.

So ok, problems with building: 
1) pycpp.py missing "#!/usr/bin/env python" string. Without this instruction script will be running by shell, not by python, as described [here](https://stackoverflow.com/questions/45849176/just-writing-import-in-a-python-script-breaks-my-mouse-cursor-forcing-a-hard-r). This leads to an endless building process.
2) functions "setExtVersion" and "setBuildDate" (src/sim_ros_interface.cpp:647-648) was not declared. With commenting them build is successful.

I am using last versions of copelliaSim and simExtROSInterface.

**Comment by fferri** [comment]
Please clarify what you mean with the tutorial at https://www.coppeliarobotics.com/helpFiles/en/ros1Tutorial.htm not being "actual". It looks correct to me.

About the cmake version, 3.10 is already old. You can upgrade to Ubuntu 20.04 which ships with 3.16, or use Kitware apt repository. Make sure you use the 'melodic' branch.

Problem 1: no it doesn't need that, pycpp.py is run as argument to the Python executable, both in libPlugin and in simExtROSInterface, so the shebang is meaningless. Might be a XY problem what you are observing.

Problem 2: you need the latest version of all dependencies (CoppeliaRobotics' git repositories: include, common, simMath, libPlugin).

Next time please report only one problem per issue.
