### ISSUE TITLE
Version required does not exist?

### ISSUE THREAD

**Issue by tiagonovo0** [CoppeliaRobotics/simExtROSInterface#5]
I'm trying to compile package sim_ros_interface but when I do, an error of a required version occurs. How is that possible?
![Screenshot from 2020-07-13 15-26-53](https://user-images.githubusercontent.com/61195838/87317845-740eb380-c51f-11ea-9a24-a70cc6388f4a.png)

**Comment by YoussefHindi** [comment]
i have exactly the same issue on ubuntu 16.04

**Comment by tiagonovo0** [comment]
It looks like a beta version [4.1.0.0](https://coppeliarobotics.com/files/beta/) was released. 
I did not try it yet.
