### ISSUE TITLE
Undeclared functions: setExtVersion() and  setBuildDate()

### ISSUE THREAD

**Issue by ritalaezza** [CoppeliaRobotics/simExtROSInterface#6]
When calling `catkin build --cmake-args -DCMAKE_BUILD_TYPE=Release` there are two functions in the **sim_ros_interface.cpp** which are not declared and lead to a failed build. These are `setExtVersion()` and  `setBuildDate()`. 

I am using the melodic branch.

**Comment by fferri** [comment]
This plugin depends also on the following repositories (which are usually located in the *programming* folder of CoppeliaSim):
- [include](https://github.com/CoppeliaRobotics/include)
- [common](https://github.com/CoppeliaRobotics/common)
- [simMath](https://github.com/CoppeliaRobotics/simMath)
- [libPlugin](https://github.com/CoppeliaRobotics/libPlugin)

Make sure to have the latest version of each.

**Comment by ritalaezza** [comment]
I have installed CoppeliaSim EDU for Ubuntu 18.04, using the install packages provided at [https://www.coppeliarobotics.com/downloads](https://www.coppeliarobotics.com/downloads). Am I supposed to overwrite the content of the folders inside the _programming_ folder with the updated repositories? Won't that break other things?

**Comment by fferri** [comment]
Latest version of CoppeliaSim should already include the most recent code for each of these repositories.

But yes, in theory you can overwrite the content with the updated repositories. In practice, you will however need a recent version of CoppeliaSim to use the latest code in those repositories.
